### ISSUE TITLE
Presence of /var/run/docker.sock prevents docker daemon from starting

### ISSUE THREAD

**Issue by brianz** [remind101/empire_ami#1]
When launching an instance, the presence of `/var/run/docker.sock/` is preventing docker from starting.  As such, instances aren't getting registered with ECS.  Forcefully removing this directory and restarting docker seems to solve the problem.

**Comment by brianz** [comment]
FWIW, using Stacker to spin things up, there's been at least one case where this was a problem on one instance and not the other, i.e., one (of two) instance has the `/var/run/docker.sock/` directory preventing docker from starting, while the other instance _didn't_ have that directory and Docker started up just fine.

**Comment by phobologic** [comment]
I'm going to close this, since I believe #2 should fix it.  If you see it again, let me know!
