### ISSUE TITLE
Logs are lost if logspout is started after ecs_agent

### ISSUE THREAD

**Issue by crohr** [remind101/empire_ami#19]
In some cases when provisioning a new minion, the ecs_agent will be fully up and running before logspout has started, which means any task scheduled on that host will have its logs not picked up by the (not yet running) logspout container.

The solution would be to make `ecs_agent.conf` depend on `logspout` for starting, but since `logspout` is optional we can't just add `start on (started logspout)`.

Did you encounter the same issue on your side, and how do you deal with it (restarting the process works, but is not really convenient)?

**Comment by phobologic** [comment]
The issue only lasts for the (hopefully small?) amount of time that logspout is not up, right?  When it finally comes up, it picks up on the new logs?  Or does it just never get the logs from containers that were launched when it wasn't up?

I think, as long as you use `start on (starting logspout)` you would be safe, though I haven't tested it.  Honestly, mixing ansible's service controls with upstart event chaining has proven to be a little painful for us.  We're working on a method for dealing with that better.

**Comment by crohr** [comment]
Actually you're right, it appears that logspout attaches to containers that were already started when it launches. But I was still not seeing any logs via kinesis until I restarted the app. Not sure what happened there. I'll upgrade a new platform today and I'll see if I get the same issue.

**Comment by phobologic** [comment]
Cool - yeah, let us know if you can reproduce it and then I'll try and figure out what is going on there.  We haven't seen this behavior before.

**Comment by phobologic** [comment]
Hey @crohr - any updates on this?

**Comment by crohr** [comment]
@phobologic actually yes, I had the same issue on the other platform that we upgraded. Not really sure what's happening there.

**Comment by phobologic** [comment]
Hey @crohr - can you try using this docker image for logspout, and let me knwo if that resolves it? `remind101/logspout@sha256:30c4f620e834ca662cbf5025486ae2a818efa19432a2d6a91b4c7260e35ffe61`

Thanks!
