### ISSUE TITLE
Running out of disk space

### ISSUE THREAD

**Issue by louy** [remind101/empire_ami#21]
We're having this a lot recently. Docker keeps eating up disk space until we run out of memory and suddenly all deployments fail. 

Does empire have a clean-up task?

**Comment by gileze33** [comment]
Just to add a bit more info to this - it seems like the `docker_maid` script is missing loads of images when attempting cleanup. For example `docker ps -q -f status=exited` only returns 5 images, when I can see about 50 that are still hanging around and need removing.

**Comment by gileze33** [comment]
As another note - I've been looking around and it seems like the best solution is actually to try and remove all images and containers (without forcing) and letting it issue warnings on any still running.

This seems to work pretty well, and leaves running images/containers hanging about absolutely fine - would you guys like us to submit a PR to change to using this?

`docker rmi $(grep -xvf <(docker ps -a --format '{{.Image}}') <(docker images | tail -n +2 | grep -v '<none>' | awk '{ print $1":"$2 }'))`

**Comment by phobologic** [comment]
@louy the docker_maid script should handle this for you, though it seems there might be an issue?

@gileze33 `docker ps` should be showing the non-running containers, and removing those first.  Then the `docker images -f "dangling=true" -q` should be finding all the non-used images.  Can you verify that that is not working?  Any idea what 'status' the containers are in that `docker ps` isn't finding?

**Comment by louy** [comment]
@phobologic me and @gileze33 are on the same team and had the same issue. basically it looks like `"dangling=true"` doesn't output all undesired images. personally I use `docker rm $(docker ps -q) && docker rmi $(docker images -q)` which is much simpler and guaranteed to work.

**Comment by phobologic** [comment]
Yeah, I think the original maid actually just deleted anything that docker would let it, but we were concerned about running into some bug that resulted in brokeness.  That was a bit of overly-defensive thinking most likely.  If you guys want to submit a PR, I'd be up for it!  I'd love to know what images you guys have that aren't in dangling (and what state they are in) that should be deleted as well!

Thanks!

**Comment by gileze33** [comment]
I spent quite a while the other evening trying to work out what `status` the other images were in, with absolutely no luck. It seems from the number of SO items and issues on the docker repo that this is a pretty common bug bear with docker.

I have a feeling that actually the suspect images are ones within the same dockerhub repo as other images that happen to be still running (with a newer version) on the same instance. It really becomes a problem when you have a ton of services that are moving about a lot when you deploy often (we run 18 `t2.medium` with 57 services in production...)

**Comment by phobologic** [comment]
Wow!  That's some container density you guys have going, that's awesome :)

Like I said, we were being (possibly over) cautious, since we were putting this out in the OSS world and didn't want to accidentally delete something that people didn't want deleted.  I'm fine with being a bit more aggressive if it will help, just need to be relatively confident that the solution won't put us in a bad place. :)
