### ISSUE TITLE
awscli from pip instead of Ubuntu packages?

### ISSUE THREAD

**Issue by ianneub** [remind101/empire_ami#9]
Howdy, I was wondering if you would be ok with a PR that switched awscli from being installed by the Ubuntu package to being installed by pip.

The Ubuntu package is quite a bit out of date (1.2.9 vs 1.8.13) and doesn't support things like Lambda that I happen to need.

What do you think? Can we switch to pip? 

Thanks.

**Comment by phobologic** [comment]
Sounds good to me!  Should be an easy change.
